[tool.poetry]
name = "tkc-lvlab"
version = "v0.1.0"
description = "The Libvirt Labs project provides the `lvlab` Python application which can be used to manage Libvirt based development environments in a familiar way."
authors = ["Chris Row <1418370+memblin@users.noreply.github.com>"]
readme = "README.md"
include = ["tkc_lvlab/templates/*.j2"]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
pyyaml = "^6.0.1"
tqdm = "^4.66.4"
requests = "^2.32.3"
libvirt-python = "^10.5.0"
python-gnupg = "^0.5.2"
jinja2 = "^3.1.4"
pycdlib = "^1.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
lvlab = "tkc_lvlab.cli:run"
