sonar.projectKey=tkc-lvlab-py
sonar.host.url=http://sonar.tkclabs.io:9000

sonar.sources=tkc_lvlab
sonar.tests=tests
sonar.python.version=3.11,3.12,3.13,3.14

sonar.python.coverage.reportPaths=coverage.xml
