name: build-release

on:
  workflow_dispatch:
    inputs:
      description: 'Tag to build'
      required: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v3
    - name: Install poetry
      run: |
        pip install -r requirements.txt
        poetry build
